# workflow name
name: Generate release-artifacts

# on events
on:
  push:
    branches:
      - main

# workflow tasks
jobs:
  build:
    name: Builds go application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Build for Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o dist/smbrsync.exe
      - name: Build for Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o dist/smbrsync
      - name: Build for MacOS
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -o dist/smbrsync
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: dist/